version: "3.7"

services:
  exchange-rate-api:
    image: exchange-rate-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ../:/usr/src/app/
    ports:
      - 4000:80
      - 10020:10000
    environment:
      - DEBUGGER=True
      - ENVIRONMENT=dev
      - APP_VERSION=0.1.0
      - APP_TITLE=Exchange Rate API
      - APP_DESCRIPTION=Exchange rate API
      - DATABASE_HOST=exchange-db
      - DATABASE_NAME=exchange_db_dev
      - DATABASE_TEST_NAME=exchange_db_test
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - OFFICIAL_RATE_SITE=https://www.banxico.org.mx/tipcamb/tipCamMIAction.do
      - FIXER_API=http://data.fixer.io/api/latest
      - FIXER_API_KEY=f9aff0ccbc4b5bc563017d44b88928d1
      - BANXICO_API=https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718/datos
      - BANXICO_TOKEN=700bd6f4d875c0f527001edb1737db29caff831b0b8e25b3e5baa77f83f19e1c
      - RATE_LIMIT_PER_USER=10
    networks:
     - exchange

  exchange-db:
    image: exchange-db
    build:
      context: ../db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - exchange_data:/var/lib/postgresql/data
    networks:
      - exchange


networks:
  exchange:
   external: true

volumes:
  exchange_data:
   external: true
