version: "3.2"

services:
  exchange-rate-api:
    image: exchange-rate-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ../:/usr/src/app/
      - ../key/:/key
    ports:
      - 8009:80
      - 10019:10000
    environment:
      - DEBUGGER=True
      - ENVIRONMENT=dev
      - APP_VERSION=0.1.0
      - APP_TITLE=Exchange Rate API
      - APP_DESCRIPTION=Exchange rate API
